framework:
  test: "all"
  minimum_required_memory: 6000 # specified in MB: e.g. 6000 = (6GB) of minimum required system memory for some test cases

network:
  name: "testnet"
  mode: "api"
  rpc_prefix: "hmy"
  timeout: 0 # If set to > 0 - use this as a global timeout for all transactions
  cross_shard_tx_wait_time: 60 # The time to wait for account balances to properly updated when performing cross shard transfers - this time will be 1.5x'd for localnet, the open staking network and the stress test network since they seem to be slower with processing txs and blocks
  staking_wait_time: 30

  # endpoints should map to correct chan ids
  endpoints:
    localnet:
      - http://localhost.charlesproxy.com:9500
      - http://localhost.charlesproxy.com:9501
    pangaea:
      - http://35.166.89.131:9500
      - http://18.222.166.227:9500
      - http://3.101.57.60:9500
      - http://3.85.9.70:9500
    stressnet:
      - http://54.245.77.197:9500
      - http://52.53.161.58:9500
  
  retry: # Retry settings for common RPC calls (if used). Can be overriden by specific RPC functionality (e.g. balances)
    attempts: 3 # How many attempts that should be performed per RPC call
    wait: 1 # How long to wait after each attempt
  
  balances:
    retry:
      attempts: 25
      wait: 5
  
  gas:
    cost: 0.1 # Estimated gas cost that will be used for various transaction and funding calculations etc.
    limit: -1 # Higher limit than regular txs (21000) - seems there are some issues occasionally when using a lower gas limit 
    price: 1

account:
  passphrase: ""
  remove_empty: true
  use_all_in_keystore: false
  
funding:
  account:
    name: "FundingAccount" # This name will be prefixed with the current network name
    address: ""
  shards: "all"
  minimum_funds: 10.0
  timeout: 60
  verbose: false
  retry:
    attempts: 5 # How many funding attempts that should be performed
    wait: 1 # How long to wait after each attempt
  gas:
    cost: 0.0001
    limit: -1
    price: 1
